# https://docs.docker.com/compose/compose-file
# docker-compose up
# docker-compose stop
# docker-compose down
version: '3'

#networks:
#  shared-network:
#    driver: bridge

services:
  # This is the core CRUD based service.
  users-api:
    container_name: users-api
#    networks:
#      - shared-network
    image: igorgomonov/users-api-amd64:1.0
    ports:
      - 5000:5000 # CRUD API
      - 6000:6000 # DEBUG API
    environment:
      - USERS_DB_HOST=db
      - USERS_DB_DISABLE_TLS=1 # This is only disabled for our development enviroment.
      # - GODEBUG=gctrace=1
